### PR TITLE
Attack container shell enhancements

### PR DESCRIPTION
**Pull request by sublimino**
- run ssh-keyscan on attack nodes to avoid prompting user for key identification
- modify prompt to include status code of last command
- do not require an argument if only one target to choose from in attack_master/node
- add bash-completion and man pages to attack container
- add .inputrc and bash_aliases from simulator container
- enable bash completion
- add docs for testing 

Tested via the mechanism described in contributing.md, taken from the PR content in #43 

This has been tested using the exact instructions in contributing.md, e.g. `CONTAINER_TAG=super-cool-feature make docker-push` and `simulator infra create --attack-container-tag=super-cool-feature`

### CODE REVIEW

**Comment by jondkent** [comment]
Andy,

Can you look at the contributing section at the end of the current README.  Probably better to have this in a standalone file anyway, as this is too hidden within the README, and would follow GitHub's recommendations.  Was gonna do this next week, but as you are ahead :)

You'd either need to modify the `generate-docs-from-templates.sh` script, or just make it a static file, which I'd recommend tbh - see my comment on issue [51](https://github.com/kubernetes-simulator/simulator/issues/51)

Cheers,
Jon

**Comment by sublimino** [comment]
@jondkent I didn't really want to get into fixing #51 in this PR, but I have moved the contributing sections into `contibuting.md` and edited README.md.

There's a warning about doing this at the top of README.md so I'm a bit nervous -- will I break workflows with this approach? Change made in https://github.com/kubernetes-simulator/simulator/pull/57/commits/0fde580e0b9556ecf592f887ee245f53b96cf761 and I'll roll it back if it's breaking.

**Comment by raoulmillais** [comment]
Yup I think we can deal with #51 ourselves next week.  @pi-unnerup is creating documentation for contributing scenarios and we have a protocol meeting so we can make sure we're all aligned and agree on the contributing guidelines then

**Comment by raoulmillais** [comment]
I think this looks good to merge.  I'm just going to clone and test it first now

**Comment by sublimino** [comment]
> I just spotted we don't continuously run the attack container tests  can we add a step in the root Makefile to cd into the attack folder and run `make docker-test` there please?

Addressed in https://github.com/kubernetes-simulator/simulator/pull/57/commits/cd40ae6c8a2fe687e45cd480c049e4ee0f60f941

**Comment by jondkent** [comment]
@sublimino don't worry, wasn't expecting you to fix anything, more thinking about what did exists already in README, issue 51 pointed out for static contrib potentials

Jon

**Pull request merged**
