### PR TITLE
Perturb refactor to hide output

### LINKED ISSUE #74: Perturb is showing ioctl errors.
**Describe the bug**
perturb is producing the following error:

`mesg: ttyname failed: Inappropriate ioctl for device`

This is not causing any issues, but needs to be addressed

**To Reproduce**
1. Start launch container
2. Create infrastructure
3. Launch scenario
4. See error on output

**Expected behavior**
Only produce usable errors

**Environment (please complete the following information):**
 - OS: MacOS 10.15
 - Docker: 2.1.0.3(38240)
 - Version of simulator: master

### PR DESCRIPTION
**Pull request by s-irvine**
Large refactor of perturb to hide extraneous `stdout` and `stderr` output.  Changes of note include:

* `warnings` are mostly replaced with `info`s so users don't see red text during normal operation.
* `info` and `success` no longer redirect to `stderr` so output at the correct time in the script instead of sitting in `stderr` until script completion.
* `info` outputs in blue for use across light and dark terminals.
* The `find_scenario` function is brought into the script and fixed to function properly. 
* `test_funcs.sh` is deprecated and commented out as no functions in there are being used.
* Since `found_scenario` is now functional, a minor change was made to replace the `lock_perturb` functions with more granular functionality. 
* Scenario challenge hashes are stored on the cluster so they will still match despite templating the challenge during the apply steps.
*  'slaves' is replaced with 'nodes' throughout the script to reflect proper kubernetes project terminology.
* trivial edits to the go and tests were made to support this
* nodes are now tested for connectability as well as the master.
* master and node connection tests are moved to earlier in the script before any commands to those hosts are run.
* ioctl errors have been fixed by editing the bash profile on the remote servers.
* scenarios log output to local log file that is deleted on success.
* scenarios have redirects to `/dev/null` removed as this is now handled by perturb.

Fixes #74  #91 

Depends on #132

### CODE REVIEW

**Comment by s-irvine** [comment]
Functions for checking connectivity have been unified into one function and pod readiness is actually tested instead of just waiting 30 seconds.

**Comment by jondkent** [comment]
As you're tidying up the code base, I believe that :

`if test "$BASH" = "" || "$BASH" -uc 'a=();true "${a[@]}"'`

is an over the top way of testing bash version, which has a better test (read more obvious) on line 36.

If thats correct you may want to change that

**Comment by s-irvine** [comment]
Shellcheck fixed

**Comment by s-irvine** [comment]
> As you're tidying up the code base, I believe that :
> 
> `if test "$BASH" = "" || "$BASH" -uc 'a=();true "${a[@]}"'`
> 
> is an over the top way of testing bash version, which has a better test (read more obvious) on line 36. If thats correct you may want to change that
> 
> I'm not sure why
> 
> `IS_DRY_RUN=0`
> 
> exists tbh, only used once within the script (line 502). Seems a little unnessary imho and therefore up for removal?
> 
> Line 178 can be removed, old code from me no longer required.
> 
> The `get_node_ips` function has DigitalOcean code in it (`doctl`). Is this, and the following 2 functions, still required?

I've removed the commented code as that's trivial. The rest have no functional impact on this PR and exceed its scope. I think they should go into their own PR once this is merged.

**Pull request merged**
