### PR TITLE
fix: create parent directory before create file in OverwriteFile

### PR DESCRIPTION
**Pull request by tomoyamachi**
First of all, I want to provide my deep respect for this project. It is a fantastic project. 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows the conventional commits guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Fail to create `.kubesim/settings/bastion.tfvars` at first time.

* **What is the new behavior (if this is a feature change)?**
Create `.kubesim/settings` dir before create `./kubesim/settings/bastion.tfvars`

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

### CODE REVIEW

**Comment by raoulmillais** [comment]
Awesome thanks for this and thanks for properly updating the tests 😀

**Comment by raoulmillais** [comment]
@tomoyamachi can you rebase and GPG sign your commit please?  I can't merge unless you do that.

**Comment by tomoyamachi** [comment]
@raoulmillais 
Thank you for your review. I signed it.

**Comment by raoulmillais** [comment]
Thanks @tomoyamachi :)

**Pull request merged**
