### PR TITLE
Build speedup

### LINKED ISSUE #149: simulator takes far too long to compile
**Describe the bug**
When you compile kubesim from scratch it currently takes over 30 mins to complete.

Even when you re-run `make run` this also take a very long time to complete.  This appears to be caused by the large number of external libraries required.

### PR DESCRIPTION
**Pull request by raoulmillais**
**This PR supercedes #150 with the same commits but GPG signed**

This pull request changes the static analysis to use golangci-lint which is 5x faster than using the tools separately and adds a lot more checks and fewer false positives.

I have fixed all the existing problems as separate commit: I had to fix a lot of missing error handling so please pay close attention to that commit

This ~~partially~~ fixes #149 ~~but more investigation is needed to investigate why module downloading has slowed considerably~~

### CODE REVIEW

**Comment by abdullahgarcia** [comment]
Found the following bug:

panic: sync /dev/stderr: invalid argument

goroutine 1 [running]:
github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand.func1(0xc00000e0c8)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:44 +0x58
github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand(0xc0001a7180)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:50 +0x1be
github.com/controlplaneio/simulator-standalone/cmd.newCmdRoot(0x0)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:29 +0x196
github.com/controlplaneio/simulator-standalone/cmd.Execute(0xb, 0xbac7ec)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:124 +0x22
main.main()
    /go/src/github.com/controlplaneio/simulator-standalone/main.go:13 +0x26
panic: sync /dev/stderr: invalid argument

goroutine 1 [running]:
github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand.func1(0xc00000e0c8)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:44 +0x58
github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand(0xc0001a5180)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:50 +0x1be
github.com/controlplaneio/simulator-standalone/cmd.newCmdRoot(0x0)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:29 +0x196
github.com/controlplaneio/simulator-standalone/cmd.Execute(0xb, 0xbac7ec)
    /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:124 +0x22
main.main()
    /go/src/github.com/controlplaneio/simulator-standalone/main.go:13 +0x26

**Comment by raoulmillais** [comment]
> Found the following bug just after the "Simulator" red header:
> 
> ```
> panic: sync /dev/stderr: invalid argument
> 
> goroutine 1 [running]:
> github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand.func1(0xc00000e0c8)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:44 +0x58
> github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand(0xc0001a7180)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:50 +0x1be
> github.com/controlplaneio/simulator-standalone/cmd.newCmdRoot(0x0)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:29 +0x196
> github.com/controlplaneio/simulator-standalone/cmd.Execute(0xb, 0xbac7ec)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:124 +0x22
> main.main()
>     /go/src/github.com/controlplaneio/simulator-standalone/main.go:13 +0x26
> panic: sync /dev/stderr: invalid argument
> 
> goroutine 1 [running]:
> github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand.func1(0xc00000e0c8)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:44 +0x58
> github.com/controlplaneio/simulator-standalone/cmd.newConfigCommand(0xc0001a5180)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/config.go:50 +0x1be
> github.com/controlplaneio/simulator-standalone/cmd.newCmdRoot(0x0)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:29 +0x196
> github.com/controlplaneio/simulator-standalone/cmd.Execute(0xb, 0xbac7ec)
>     /go/src/github.com/controlplaneio/simulator-standalone/cmd/root.go:124 +0x22
> main.main()
>     /go/src/github.com/controlplaneio/simulator-standalone/main.go:13 +0x26
> ```

https://github.com/uber-go/zap/issues/370 this is a bug in zap and they have no plans to fix it.  We are migrating to logrus imminently so I will just remove the panic for now

**Comment by raoulmillais** [comment]
https://github.com/kubernetes-simulator/simulator/pull/151/commits/8923de6a664f0f23e844639ca3d126971f9e5628 "fixes" your reported issue @abdullahgarcia 

https://github.com/kubernetes-simulator/simulator/pull/151/commits/c351e8bf52667310a4b6e6f1e6b0ffcce857ee4f massively speeds up the build (ran `go mod tidy` to cleanup dependencies)

**I had to force push because I accidentally pushed a broken commit, please delete your local branch and refetch it from origin before testing**

**Comment by s-irvine** [comment]
Simulator no longer displays the help text once it's done building for me.

image

**Comment by raoulmillais** [comment]
@s-irvine that is now fixed... **I force pushed** after interactively rebasing to drop a broken commit and edit the commit which fixes missing error handling.

@jondkent build times are now sane again

**Please delete your local branch and refetch from origin before retesting**

**Comment by jondkent** [comment]
This is much better now, and much faster.  LGTM

**Comment by s-irvine** [comment]
I've done a `simulator infra create`, `simulator infra destroy` and `simulator scenario launch` and everything looks to be working well atm.

**Pull request merged**
