### PR TITLE
feat: upgrade to terraform 13

### LINKED ISSUE #296: Upgrade to terraform 0.13
Upgrade to terraform 0.13 using `terraform 0.13upgrade`.

### PR DESCRIPTION
**Pull request by s-irvine**
Fixes #296

### CODE REVIEW

**Review by jondkent — COMMENTED** [review]
Can you outline why you added the versions.tf to each terraform module, seems to be adding maintaince overhead

**Comment by s-irvine** [comment]
The `versions.tf` is standard terraform syntax now in TF 0.13. Thanks to the new [provider source](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations) feature all non-hashicorp modules *need* to have a source defined in the code and it's good practice to also define the source for the hashiscorp modules. The upgrade tool did this automatically so I figured it was worth leaving in.

**Review by jondkent — APPROVED** [review]
LGTM

**Review by pi-unnerup — APPROVED** [review]
lgtm

**Pull request merged**
