### PR TITLE
feat: allow extra ips to be added to the bastion sg

### LINKED ISSUE #164: Add arbitrary IPs to the Simulator Security Groups
**Feature statement**
At the moment simulator only allows access to the cluster from the specific IP that created it. It would be very useful to allow a user to specify an IP or CIDR so they can access the cluster from a known internet location. This would ease one of the quiet user experience issues we have and allow users to mitigate issues with IP changes due to intermediate networking.

**Proposed approach**
Ideally a user would be able to specify these IPs/CIDRs on the cli with some `--` options and be able to run a specific `simulator` command. There should also be a command and `--` options to remove specific CIDRs/ IPs, including the ones automatically discovered by simulator. The IPs and CIDRs should survive a `simulator infra create` but not a `simulator infra destroy`.

### PR DESCRIPTION
**Pull request by s-irvine**
Users can now specify CIDRs to be added to the bastion security group with the `--extra-cidrs` flag.

Resolves #164

### CODE REVIEW

**Comment by jondkent** [comment]
Reviewing

**Comment by raoulmillais** [comment]
This is great how about making IP detection optional entirely?

**Comment by pi-unnerup** [comment]
I can not make this work. To replicate try
- create infra on workspace network with -e <ip>/32 where ip is your ip on the second network
- simulator ssh attack on new network (I have tried both dot11 in workspace and android)

**Comment by pi-unnerup** [comment]
> This is great how about making IP detection optional entirely?

https://github.com/kubernetes-simulator/simulator/issues/232 made a ticket here

**Comment by s-irvine** [comment]
> I can not make this work. To replicate try
> 
> * create infra on workspace network with -e /32 where ip is your ip on the second network
> * simulator ssh attack on new network (I have tried both dot11 in workspace and android)

I've managed to replicate the issue and I think it's to do with the IP detection breaking. The SSH command is not actually run because IP detection fails before it gets there. I think #232 will fix this issue by allowing us to disable IP detection.

**Pull request merged**
