### PR TITLE
Ssh state management

### PR DESCRIPTION
**Pull request by raoulmillais**
- Creates a new state provider abstraction for SSH state related things (keys and config)
- Removes confusing unused SSH agent support
- Reduces the frequency of reading and writing SSH files from / to disk
- Creates strong types for SSH public keys and private keys to avoid
  mistakes mixing them up
- Introduces a new SSH keypair type
- Splits key loading and writing logic from business logic for preparing
  the keys for use
- Stops mounting the user's ~/.ssh directory which they might quite rightly be concerned about and moves all the SSH config and keys into the ~/.kubesim folder for consistency
- Renames the go module to match the repo (from controlplaneio/simulator-standalone)
- Fixes flickering unit tests because of pre-existing SSH keys

Everything should just work the same from the users perspective (other than the move of the location of the SSH keys and config, but that's not obvious to them)

### CODE REVIEW

**Comment by raoulmillais** [comment]
I'm about to force push to fix the conflict and squash the WIP commit that crept in

**Comment by raoulmillais** [comment]
Hmm, this is happening because I have moved the SSH keys into the kubesim folder and you have an existing `bastion.tfvars` file telling simulator its in the ~/.ssh folder.  The cleaned up log is:
```
No file exists at
/home/launch/.ssh/cp_simulator_rsa
````

which is true!  I no longer mount `~/.ssh`

**Comment by raoulmillais** [comment]
Ok this should now be fixed.  I've updated the correct new location for the ssh key everywhere

**Comment by jondkent** [comment]
well you have fixed the initial problem, now got an issue launching a scenario:

`INFO[2020-03-12T14:20:18Z] Running terraform output
INFO[2020-03-12T14:20:21Z] Finding details of scenario                   ScenarioID=policy-fire-support
INFO[2020-03-12T14:20:21Z] Updating SSH config
INFO[2020-03-12T14:20:21Z] Keyscanning bastion and updating known hosts  BastionIP=15.188.146.250
INFO[2020-03-12T14:20:21Z] Setting up the scenario on the cluster        Scenario="Policy Fire Support"
ERRO[2020-03-12T14:20:21Z] Cannot connect to 172.31.2.95                 Args="[--master 172.31.2.95 --bastion 15.188.146.250 --nodes 172.31.2.163,172.31.2.55 policy-fire-support]" Command=./perturb.sh
ERRO[2020-03-12T14:20:21Z] Error launching scenario                      Error="Error running perturb with simulator.PerturbOptions{Bastion:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xf, 0xbc, 0x92, 0xfa}, Master:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x5f}, Slaves:[]net.IP{net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0xa3}, net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xac, 0x1f, 0x2, 0x37}}, ScenarioName:\"policy-fire-support\"}: Error waiting for child process ./perturb.sh: exit status 3"`
`simulator ssh attack works` fine btw

**Comment by raoulmillais** [comment]
This is now fixed

**Pull request merged**
